/*
 * THIS FILE IS MACHINE-GENERATED. DO NOT EDIT.
 *
 * Content generated by Echelon IzoT Interface Interpreter 1.10.07 at 10-Aug-2019 16:22
 * Copyright (c) Echelon Corporation 2014-2015
 *
 * Target: Echelon IzoT ShortStack (SS430_FT6050_SYS20000kHz)
 *
 * Use of this code is subject to your compliance with the terms of the
 * Echelon IzoT(tm) ShortStack License Agreement which is
 * available at www.echelon.com
 */
#ifndef DEFINED_SHORTSTACKDEV_H
    /* Define macro derived from the current output name */
#   define DEFINED_SHORTSTACKDEV_H

#define LON_FRAMEWORK_TYPE_III 1

#include <stddef.h>
#include "LonPlatform.h"

/*
 * Data type definitions
 */
typedef LON_STRUCT_BEGIN(SNVT_str_asc) {
    LonByte ascii_[31];
} LON_STRUCT_END(SNVT_str_asc);

typedef LON_STRUCT_BEGIN(SNVT_switch) {
    LonByte value;
    LonBits8 state;
} LON_STRUCT_END(SNVT_switch);

typedef LonWord SNVT_count;

typedef LonWord SNVT_lev_percent;

typedef LonWord SNVT_press_p;

typedef LON_STRUCT_BEGIN(UNVTdevHandle) {
    LonByte index;
    LonByte devHandle[30];
} LON_STRUCT_END(UNVTdevHandle);

typedef SNVT_press_p SCPTductStaticPressureSetpoint;

typedef LonWord SNVT_time_sec;

typedef SNVT_time_sec SCPTdelayTime;

typedef SNVT_time_sec SCPTmeasurementInterval;

typedef SNVT_press_p SCPTmaxDuctStaticPressureSetpoint;

typedef SNVT_press_p SCPTminDuctStaticPressureSetpoint;

/* end Data type definitions */

/*
 * Block type definitions and references
 */
#define UFPTDspSPcontroller(mod)   UFPTDspSPcontroller_##mod
typedef struct {
   unsigned global_index;
   struct {
      SNVT_str_asc data;
      unsigned global_index;
   } nviAddRouge;
   struct {
      SNVT_switch data;
      unsigned global_index;
   } nviEnable;
   struct {
      SNVT_str_asc data;
      unsigned global_index;
   } nviRemoveRouge;
   struct {
      SNVT_count data;
      unsigned global_index;
   } nviShowRouge;
   struct {
      SNVT_lev_percent data;
      unsigned global_index;
   } nvoAvgDemand;
   struct {
      SNVT_press_p data;
      unsigned global_index;
   } nvoDspSP;
   struct {
      SNVT_lev_percent data;
      unsigned global_index;
   } nvoMaxDemand;
   struct {
      SNVT_lev_percent data;
      unsigned global_index;
   } nvoMinDemand;
   struct {
      SNVT_count data;
      unsigned global_index;
   } nvoRougeCount;
   struct {
      UNVTdevHandle data;
      unsigned global_index;
   } nvoRougeReport;
   SCPTductStaticPressureSetpoint* cpDefaultDspSP;
   SCPTdelayTime* cpDelay;
   SCPTmeasurementInterval* cpLoopInterval;
   SCPTmaxDuctStaticPressureSetpoint* cpMaxDspSP;
   SCPTminDuctStaticPressureSetpoint* cpMinDspSP;
} UFPTDspSPcontroller_DspCntl;

extern UFPTDspSPcontroller_DspCntl DspCntl;

#define LON_FB_COUNT 1
/* end Block type definitions and references */

/*
 * Device datapoint references
 */
/* end Device datapoint references */

/*
 * Device property references
 */
/* end Device property references */

/*
 * Message tag references
 */
/* end Message tag references */

#define LON_NV_COUNT 15
/* For compatibility with older ShortStack applications */
#define LonNvCount LON_NV_COUNT
#define LON_PERSISTENT_NVS 5
#define LON_MT_COUNT 0
/* For compatibility with older ShortStack applications */
#define LonMtCount LON_MT_COUNT

#define LON_APP_OUTPUT_BUFSIZE 146
#define LON_APP_INPUT_BUFSIZE 146
#define LON_ISI_ENABLED 0x00
#define LON_USE_DEFAULT_COMMPARAMS 0x40 /* see LonCustomCommunicationParameters() */
#define LON_APP_SIGNATURE 0xBE7B47DA
#define LON_APPLICATION_MESSAGES 0
#define LON_SERVICE_PIN_TIMER 0
#define LON_PROGRAM_ID "90:00:01:06:00:03:85:00"

#define LON_NM_QUERY_FUNCTIONS 0
#define LON_NM_UPDATE_FUNCTIONS 0
#define LON_UTILITY_FUNCTIONS 0

#define LON_DMF_WINDOW_ENABLED 0
#define LON_DMF_WINDOW_SIZE    0
#define LON_DMF_WINDOW_START   0
#define LON_DMF_ENABLED LON_DMF_WINDOW_ENABLED
#define LON_DMF_FILEINDEX_DIRECTORY 0
#define LON_DMF_FILEINDEX_TEMPLATE 1
#define LON_DMF_FILEINDEX_MODIFIABLE 2
#define LON_DMF_FILEINDEX_READONLY 3
#define LON_DMF_FILEINDEX_MAXINDEX	LON_DMF_FILEINDEX_READONLY

#define LON_EXPLICIT_ADDRESSING (LON_ISI_ENABLED | 0x20)

extern const LonByte* LonGetSiData(unsigned* pLength);
extern const LonByte* LonGetAppInitData(void);
extern void* LonGetNvTable(void);
extern unsigned LonGetNvCount(void);
extern unsigned LonGetMtCount(void);
extern LonUbits32 LonGetSignature(void);
extern void* LonGetFile(int file_index, unsigned* pSize);
extern void LonFrameworkInit(void);

#ifndef DEFINED_SHORTSTACKDEV_H
    /* Define this unless same as output name */
#   define DEFINED_SHORTSTACKDEV_H
#endif
#endif   /* DEFINED_SHORTSTACKDEV_H */
