# Copyright (C) 2013-2023 Echelon Corporation.  All Rights Reserved.
# Use of this code is subject to your compliance with the terms of the
# Echelon IzoT(tm) Software Developer's Kit License Agreement which is
# available at www.echelon.com/license/izot_sdk/.

# IzoT resources contained in this file are generated by an automated
# database to source code conversion process.  Grammar and punctuation within
# the embedded documentation may not be correct, as this data is gathered and
# combined from several sources.
# Names of resources and fields or members defined within a resource are
# derived from the same sources.  Names, capitalization and aspects of source
# code formatting may fail to comply with PEP-8 and PEP-257 recommendations
# due to the automated generation of these IzoT definitions.
# Generated at 11-May-2023 17:11.

"""caProcessor userdefined profile, originally defined in resource file set
apollodev 90:00:01:06:00:00:00:00-4."""


import izot.resources.base
from P9000010600000000_4.userdefined import userdefined
import P9000010600000000_4.datapoints.capAlarm
import P9000010600000000_4.datapoints.capState
import P9000010600000000_4.datapoints.enable
import P9000010600000000_4.properties.capConfig


class caProcessor(izot.resources.base.Profile):
    """caProcessor userdefined profile.  """

    def __init__(self):
        super().__init__(
            key=20033,
            scope=4
        )
        self.datapoints['nvoAlarm'] = izot.resources.base.Profile.DatapointMember(
            doc=""" """,
            name='nvoAlarm',
            profile=self,
            number=1,
            datatype=P9000010600000000_4.datapoints.capAlarm.capAlarm,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.OUTPUT
        )
        self.datapoints['nvoCapState'] = izot.resources.base.Profile.DatapointMember(
            doc=""" """,
            name='nvoCapState',
            profile=self,
            number=2,
            datatype=P9000010600000000_4.datapoints.capState.capState,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.OUTPUT
        )
        self.datapoints['nviEnable'] = izot.resources.base.Profile.DatapointMember(
            doc=""" """,
            name='nviEnable',
            profile=self,
            number=3,
            datatype=P9000010600000000_4.datapoints.enable.enable,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.INPUT
        )
        self.properties['cpConfig'] = izot.resources.base.Profile.PropertyMember(
            doc=""" """,
            name='cpConfig',
            profile=self,
            number=1,
            datatype=P9000010600000000_4.properties.capConfig.capConfig,
            default=b'\x00\x00\x00\x00\x00\x00\x00\x00',
            mandatory=True
        )
        self._original_name = 'UFPTcaProcessor'
        self._definition = userdefined.add(self)
        self.finalize()


if __name__ == '__main__':
    # unit test code.
    item = caProcessor()
    pass
