# Copyright (C) 2013-2023 Echelon Corporation.  All Rights Reserved.
# Use of this code is subject to your compliance with the terms of the
# Echelon IzoT(tm) Software Developer's Kit License Agreement which is
# available at www.echelon.com/license/izot_sdk/.

# IzoT resources contained in this file are generated by an automated
# database to source code conversion process.  Grammar and punctuation within
# the embedded documentation may not be correct, as this data is gathered and
# combined from several sources.
# Names of resources and fields or members defined within a resource are
# derived from the same sources.  Names, capitalization and aspects of source
# code formatting may fail to comply with PEP-8 and PEP-257 recommendations
# due to the automated generation of these IzoT definitions.
# Generated at 11-May-2023 17:11.

"""dailyReboot userdefined profile, originally defined in resource file set
apollodev 90:00:01:06:00:00:00:00-4."""


import izot.resources.base
from P9000010600000000_4.userdefined import userdefined
import P9000010600000000_4.properties.rebootTm
import P9000010600000000_4.properties.stackOffTime
import P9000010600000000_4.properties.restartMode


class dailyReboot(izot.resources.base.Profile):
    """dailyReboot userdefined profile.  """

    def __init__(self):
        super().__init__(
            key=20024,
            scope=4
        )
        self.properties['cpRebootTm'] = izot.resources.base.Profile.PropertyMember(
            doc=""" """,
            name='cpRebootTm',
            profile=self,
            number=1,
            datatype=P9000010600000000_4.properties.rebootTm.rebootTm,
            default=b'\x00\x00',
            mandatory=True
        )
        self.properties['cpStackOffTime'] = izot.resources.base.Profile.PropertyMember(
            doc=""" """,
            name='cpStackOffTime',
            profile=self,
            number=2,
            datatype=P9000010600000000_4.properties.stackOffTime.stackOffTime,
            default=b'\x00\x00',
            mandatory=True
        )
        self.properties['cpRestartMode'] = izot.resources.base.Profile.PropertyMember(
            doc=""" """,
            name='cpRestartMode',
            profile=self,
            number=3,
            datatype=P9000010600000000_4.properties.restartMode.restartMode,
            default=b'\x01',
            mandatory=True
        )
        self._original_name = 'UFPTdailyReboot'
        self._definition = userdefined.add(self)
        self.finalize()


if __name__ == '__main__':
    # unit test code.
    item = dailyReboot()
    pass
