# Copyright (C) 2013-2023 Echelon Corporation.  All Rights Reserved.
# Use of this code is subject to your compliance with the terms of the
# Echelon IzoT(tm) Software Developer's Kit License Agreement which is
# available at www.echelon.com/license/izot_sdk/.

# IzoT resources contained in this file are generated by an automated
# database to source code conversion process.  Grammar and punctuation within
# the embedded documentation may not be correct, as this data is gathered and
# combined from several sources.
# Names of resources and fields or members defined within a resource are
# derived from the same sources.  Names, capitalization and aspects of source
# code formatting may fail to comply with PEP-8 and PEP-257 recommendations
# due to the automated generation of these IzoT definitions.
# Generated at 11-May-2023 17:11.

"""deviceMonitor userdefined profile, originally defined in resource file set
apollodev 90:00:01:06:00:00:00:00-4."""


import izot.resources.base
from P9000010600000000_4.userdefined import userdefined
import P9000010600000000_4.datapoints.enable
import izot.resources.datapoints.count_32
import P9000010600000000_4.properties.devMonTiming


class deviceMonitor(izot.resources.base.Profile):
    """deviceMonitor userdefined profile.  """

    def __init__(self):
        super().__init__(
            key=20034,
            scope=4
        )
        self.datapoints['iEnable'] = izot.resources.base.Profile.DatapointMember(
            doc=""" persistent""",
            name='iEnable',
            profile=self,
            number=1,
            datatype=P9000010600000000_4.datapoints.enable.enable,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.INPUT
        )
        self.datapoints['oRecoverdCnt'] = izot.resources.base.Profile.DatapointMember(
            doc="""Absolute count.  A 32-bit counter.""",
            name='oRecoverdCnt',
            profile=self,
            number=2,
            datatype=izot.resources.datapoints.count_32.count_32,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.OUTPUT
        )
        self.datapoints['oDownCnt'] = izot.resources.base.Profile.DatapointMember(
            doc="""Absolute count.  A 32-bit counter.""",
            name='oDownCnt',
            profile=self,
            number=3,
            datatype=izot.resources.datapoints.count_32.count_32,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.OUTPUT
        )
        self.properties['cpMonitorTiming'] = izot.resources.base.Profile.PropertyMember(
            doc=""" """,
            name='cpMonitorTiming',
            profile=self,
            number=1,
            datatype=P9000010600000000_4.properties.devMonTiming.devMonTiming,
            default=b'\x00\x3c\x07\xd0',
            mandatory=True
        )
        self._original_name = 'UFPTdeviceMonitor'
        self._definition = userdefined.add(self)
        self.finalize()


if __name__ == '__main__':
    # unit test code.
    item = deviceMonitor()
    pass
