# Copyright (C) 2013-2023 Echelon Corporation.  All Rights Reserved.
# Use of this code is subject to your compliance with the terms of the
# Echelon IzoT(tm) Software Developer's Kit License Agreement which is
# available at www.echelon.com/license/izot_sdk/.

# IzoT resources contained in this file are generated by an automated
# database to source code conversion process.  Grammar and punctuation within
# the embedded documentation may not be correct, as this data is gathered and
# combined from several sources.
# Names of resources and fields or members defined within a resource are
# derived from the same sources.  Names, capitalization and aspects of source
# code formatting may fail to comply with PEP-8 and PEP-257 recommendations
# due to the automated generation of these IzoT definitions.
# Generated at 11-May-2023 17:11.

"""dgMonitor userdefined profile, originally defined in resource file set
apollodev 90:00:01:06:00:00:00:00-4."""


import izot.resources.base
from P9000010600000000_4.userdefined import userdefined
import izot.resources.datapoints.count_inc
import P9000010600000000_4.properties.enable


class dgMonitor(izot.resources.base.Profile):
    """dgMonitor userdefined profile.  Activc Alarm Concentrator.  """

    def __init__(self):
        super().__init__(
            key=20029,
            scope=4
        )
        self.datapoints['iSbs_1alrms'] = izot.resources.base.Profile.DatapointMember(
            doc="""Increment count.  """,
            name='iSbs_1alrms',
            profile=self,
            number=1,
            datatype=izot.resources.datapoints.count_inc.count_inc,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.INPUT
        )
        self.datapoints['iSbs_2alrms'] = izot.resources.base.Profile.DatapointMember(
            doc="""Increment count.  """,
            name='iSbs_2alrms',
            profile=self,
            number=2,
            datatype=izot.resources.datapoints.count_inc.count_inc,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.INPUT
        )
        self.datapoints['iSbs_3alrms'] = izot.resources.base.Profile.DatapointMember(
            doc="""Increment count.  """,
            name='iSbs_3alrms',
            profile=self,
            number=3,
            datatype=izot.resources.datapoints.count_inc.count_inc,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.INPUT
        )
        self.datapoints['iSbs_4alrms'] = izot.resources.base.Profile.DatapointMember(
            doc="""Increment count.  """,
            name='iSbs_4alrms',
            profile=self,
            number=4,
            datatype=izot.resources.datapoints.count_inc.count_inc,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.INPUT
        )
        self.datapoints['iSbs_5alrms'] = izot.resources.base.Profile.DatapointMember(
            doc="""Increment count.  """,
            name='iSbs_5alrms',
            profile=self,
            number=5,
            datatype=izot.resources.datapoints.count_inc.count_inc,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.INPUT
        )
        self.datapoints['iSbs_6alrms'] = izot.resources.base.Profile.DatapointMember(
            doc="""Increment count.  """,
            name='iSbs_6alrms',
            profile=self,
            number=6,
            datatype=izot.resources.datapoints.count_inc.count_inc,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.INPUT
        )
        self.datapoints['iSbs_7alrms'] = izot.resources.base.Profile.DatapointMember(
            doc="""Increment count.  """,
            name='iSbs_7alrms',
            profile=self,
            number=7,
            datatype=izot.resources.datapoints.count_inc.count_inc,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.INPUT
        )
        self.datapoints['iSbs_8alrms'] = izot.resources.base.Profile.DatapointMember(
            doc="""Increment count.  """,
            name='iSbs_8alrms',
            profile=self,
            number=8,
            datatype=izot.resources.datapoints.count_inc.count_inc,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.INPUT
        )
        self.datapoints['iSbs_9alrms'] = izot.resources.base.Profile.DatapointMember(
            doc="""Increment count.  """,
            name='iSbs_9alrms',
            profile=self,
            number=9,
            datatype=izot.resources.datapoints.count_inc.count_inc,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.INPUT
        )
        self.datapoints['oSumAlrms'] = izot.resources.base.Profile.DatapointMember(
            doc="""Increment count.  """,
            name='oSumAlrms',
            profile=self,
            number=10,
            datatype=izot.resources.datapoints.count_inc.count_inc,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.OUTPUT
        )
        self.properties['cpEnable'] = izot.resources.base.Profile.PropertyMember(
            doc=""" """,
            name='cpEnable',
            profile=self,
            number=1,
            datatype=P9000010600000000_4.properties.enable.enable,
            default=b'\x00',
            mandatory=True
        )
        self._original_name = 'UFPTdgMonitor'
        self._definition = userdefined.add(self)
        self.finalize()


if __name__ == '__main__':
    # unit test code.
    item = dgMonitor()
    pass
