# Copyright (C) 2013-2023 Echelon Corporation.  All Rights Reserved.
# Use of this code is subject to your compliance with the terms of the
# Echelon IzoT(tm) Software Developer's Kit License Agreement which is
# available at www.echelon.com/license/izot_sdk/.

# IzoT resources contained in this file are generated by an automated
# database to source code conversion process.  Grammar and punctuation within
# the embedded documentation may not be correct, as this data is gathered and
# combined from several sources.
# Names of resources and fields or members defined within a resource are
# derived from the same sources.  Names, capitalization and aspects of source
# code formatting may fail to comply with PEP-8 and PEP-257 recommendations
# due to the automated generation of these IzoT definitions.
# Generated at 11-May-2023 17:11.

"""dgSensor2 userdefined profile, originally defined in resource file set
apollodev 90:00:01:06:00:00:00:00-4."""


import izot.resources.base
from P9000010600000000_4.userdefined import userdefined
import P9000010600000000_4.datapoints.dgEndpoint
import P9000010600000000_4.properties.SensorLabel
import P9000010600000000_4.properties.SerialNumber


class dgSensor2(izot.resources.base.Profile):
    """dgSensor2 userdefined profile.  """

    def __init__(self):
        super().__init__(
            key=20032,
            scope=4
        )
        self.datapoints['iState'] = izot.resources.base.Profile.DatapointMember(
            doc=""" """,
            name='iState',
            profile=self,
            number=1,
            datatype=P9000010600000000_4.datapoints.dgEndpoint.dgEndpoint,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.INPUT
        )
        self.properties['cpLabel'] = izot.resources.base.Profile.PropertyMember(
            doc=""" """,
            name='cpLabel',
            profile=self,
            number=1,
            datatype=P9000010600000000_4.properties.SensorLabel.SensorLabel,
            default=b'\x2d\x2d\x2d\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
                b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
                b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
                b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
                b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
                b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
                b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
                b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
                b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
                b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00',
            mandatory=True
        )
        self.properties['cpSn'] = izot.resources.base.Profile.PropertyMember(
            doc=""" """,
            name='cpSn',
            profile=self,
            number=2,
            datatype=P9000010600000000_4.properties.SerialNumber.SerialNumber,
            default=b'\x30\x30\x30\x30\x30\x30\x30\x30\x30\x30\x30\x30',
            mandatory=True
        )
        self._original_name = 'UFPTdgSensor2'
        self._definition = userdefined.add(self)
        self.finalize()


if __name__ == '__main__':
    # unit test code.
    item = dgSensor2()
    pass
