# Copyright (C) 2013-2023 Echelon Corporation.  All Rights Reserved.
# Use of this code is subject to your compliance with the terms of the
# Echelon IzoT(tm) Software Developer's Kit License Agreement which is
# available at www.echelon.com/license/izot_sdk/.

# IzoT resources contained in this file are generated by an automated
# database to source code conversion process.  Grammar and punctuation within
# the embedded documentation may not be correct, as this data is gathered and
# combined from several sources.
# Names of resources and fields or members defined within a resource are
# derived from the same sources.  Names, capitalization and aspects of source
# code formatting may fail to comply with PEP-8 and PEP-257 recommendations
# due to the automated generation of these IzoT definitions.
# Generated at 11-May-2023 17:11.

"""groupCntrl userdefined profile, originally defined in resource file set
apollodev 90:00:01:06:00:00:00:00-4."""


import izot.resources.base
from P9000010600000000_4.userdefined import userdefined
import izot.resources.datapoints.switch
import izot.resources.datapoints.switch_2


class groupCntrl(izot.resources.base.Profile):
    """groupCntrl userdefined profile.  """

    def __init__(self):
        super().__init__(
            key=20011,
            scope=4
        )
        self.datapoints['iLocalOvrd'] = izot.resources.base.Profile.DatapointMember(
            doc="""Switch """,
            name='iLocalOvrd',
            profile=self,
            number=1,
            datatype=izot.resources.datapoints.switch.switch,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.INPUT
        )
        self.datapoints['iRemOvrd'] = izot.resources.base.Profile.DatapointMember(
            doc="""Switch """,
            name='iRemOvrd',
            profile=self,
            number=2,
            datatype=izot.resources.datapoints.switch.switch,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.INPUT
        )
        self.datapoints['iSchedule'] = izot.resources.base.Profile.DatapointMember(
            doc="""Switch """,
            name='iSchedule',
            profile=self,
            number=3,
            datatype=izot.resources.datapoints.switch.switch,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.INPUT
        )
        self.datapoints['oDimVal'] = izot.resources.base.Profile.DatapointMember(
            doc="""Switch """,
            name='oDimVal',
            profile=self,
            number=4,
            datatype=izot.resources.datapoints.switch.switch,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.OUTPUT
        )
        self.datapoints['oDimSw2val'] = izot.resources.base.Profile.DatapointMember(
            doc="""Switch with scene and setting control.  An enhanced
            version of SNVT_switch with scene and setting controls similar to
            SNVT_scene and SNVT_setting.""",
            name='oDimSw2val',
            profile=self,
            number=5,
            datatype=izot.resources.datapoints.switch_2.switch_2,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.OUTPUT
        )
        self._original_name = 'UFPTgroupCntrl'
        self._definition = userdefined.add(self)
        self.finalize()


if __name__ == '__main__':
    # unit test code.
    item = groupCntrl()
    pass
