# Copyright (C) 2013-2023 Echelon Corporation.  All Rights Reserved.
# Use of this code is subject to your compliance with the terms of the
# Echelon IzoT(tm) Software Developer's Kit License Agreement which is
# available at www.echelon.com/license/izot_sdk/.

# IzoT resources contained in this file are generated by an automated
# database to source code conversion process.  Grammar and punctuation within
# the embedded documentation may not be correct, as this data is gathered and
# combined from several sources.
# Names of resources and fields or members defined within a resource are
# derived from the same sources.  Names, capitalization and aspects of source
# code formatting may fail to comply with PEP-8 and PEP-257 recommendations
# due to the automated generation of these IzoT definitions.
# Generated at 11-May-2023 17:11.

"""sbsControl userdefined profile, originally defined in resource file set
apollodev 90:00:01:06:00:00:00:00-4."""


import izot.resources.base
from P9000010600000000_4.userdefined import userdefined
import P9000010600000000_4.datapoints.bacnetInt
import izot.resources.datapoints.time_stamp
import P9000010600000000_4.datapoints.msgData
import P9000010600000000_4.properties.sbsTmo


class sbsControl(izot.resources.base.Profile):
    """sbsControl userdefined profile.  """

    def __init__(self):
        super().__init__(
            key=20030,
            scope=4
        )
        self.datapoints['iSentinel'] = izot.resources.base.Profile.DatapointMember(
            doc=""" """,
            name='iSentinel',
            profile=self,
            number=1,
            datatype=P9000010600000000_4.datapoints.bacnetInt.bacnetInt,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.INPUT
        )
        self.datapoints['oLastUpd'] = izot.resources.base.Profile.DatapointMember(
            doc="""Time stamp.  """,
            name='oLastUpd',
            profile=self,
            number=2,
            datatype=izot.resources.datapoints.time_stamp.time_stamp,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.OUTPUT
        )
        self.datapoints['oGwState'] = izot.resources.base.Profile.DatapointMember(
            doc=""" """,
            name='oGwState',
            profile=self,
            number=3,
            datatype=P9000010600000000_4.datapoints.msgData.msgData,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.OUTPUT
        )
        self.properties['cpSbs_tmo'] = izot.resources.base.Profile.PropertyMember(
            doc=""" Timeout for sentinel monitoring.""",
            name='cpSbs_tmo',
            profile=self,
            number=1,
            datatype=P9000010600000000_4.properties.sbsTmo.sbsTmo,
            default=b'\x00\x05',
            mandatory=True
        )
        self._original_name = 'UFPTsbsControl'
        self._definition = userdefined.add(self)
        self.finalize()


if __name__ == '__main__':
    # unit test code.
    item = sbsControl()
    pass
