# Copyright (C) 2013-2021 Echelon Corporation.  All Rights Reserved.
# Use of this code is subject to your compliance with the terms of the
# Echelon IzoT(tm) Software Developer's Kit License Agreement which is
# available at www.echelon.com/license/izot_sdk/.

# IzoT resources contained in this file are generated by an automated
# database to source code conversion process.  Grammar and punctuation within
# the embedded documentation may not be correct, as this data is gathered and
# combined from several sources.
# Names of resources and fields or members defined within a resource are
# derived from the same sources.  Names, capitalization and aspects of source
# code formatting may fail to comply with PEP-8 and PEP-257 recommendations
# due to the automated generation of these IzoT definitions.
# Generated at 25-Aug-2021 13:17.

"""_1controller userdefined profile, originally defined in resource file set
apollodev 90:00:01:06:00:00:00:00-4."""


import izot.resources.base
from P9000010600000000_4.userdefined import userdefined
import izot.resources.profiles.controller
import izot.resources.datapoints.count_f
import izot.resources.properties.nvType
import izot.resources.properties.maxNVLength
import P9000010600000000_4.properties.point
import P9000010600000000_4.properties.mathOp
import izot.resources.properties.defOutput


class _1controller(izot.resources.profiles.controller.controller):
    """_1controller userdefined profile.  """

    def __init__(self):
        super().__init__()
        self._override_scope(4)
        self.datapoints['nviDpA'] = izot.resources.base.Profile.DatapointMember(
            doc="""Absolute count.  """,
            name='nviDpA',
            profile=self,
            number=1,
            datatype=izot.resources.datapoints.count_f.count_f,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.INPUT,
            properties={
                'cpTypeInA':
                izot.resources.base.Profile.PropertyMember(
                    doc="""Network variable type.  Network variable type for
                    network variables that support changeable types.""",
                    name='cpTypeInA',
                    profile=self,
                    number=1,
                    datatype=izot.resources.properties.nvType.nvType,
                    default=b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01'
                        b'\x00\x01\x00\x00\x00\x00\x00\x00',
                    mandatory=True
                ),
                'cpNvLenA':
                izot.resources.base.Profile.PropertyMember(
                    doc="""Maximum network variable length.  Maximum length
                    of a type that may be assigned to the network
                    variable.""",
                    name='cpNvLenA',
                    profile=self,
                    number=17,
                    datatype=izot.resources.properties.maxNVLength.maxNVLength,
                    default=b'\x04',
                    mandatory=True
                )
            }
        )
        self.datapoints['nviDpB'] = izot.resources.base.Profile.DatapointMember(
            doc="""Absolute count.  """,
            name='nviDpB',
            profile=self,
            number=2,
            datatype=izot.resources.datapoints.count_f.count_f,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.INPUT,
            properties={
                'cpTypeInB':
                izot.resources.base.Profile.PropertyMember(
                    doc="""Network variable type.  Network variable type for
                    network variables that support changeable types.""",
                    name='cpTypeInB',
                    profile=self,
                    number=2,
                    datatype=izot.resources.properties.nvType.nvType,
                    default=b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01'
                        b'\x00\x01\x00\x00\x00\x00\x00\x00',
                    mandatory=True
                ),
                'cpNvLenB':
                izot.resources.base.Profile.PropertyMember(
                    doc="""Maximum network variable length.  Maximum length
                    of a type that may be assigned to the network
                    variable.""",
                    name='cpNvLenB',
                    profile=self,
                    number=18,
                    datatype=izot.resources.properties.maxNVLength.maxNVLength,
                    default=b'\x04',
                    mandatory=True
                )
            }
        )
        self.datapoints['nviDpC'] = izot.resources.base.Profile.DatapointMember(
            doc="""Absolute count.  """,
            name='nviDpC',
            profile=self,
            number=3,
            datatype=izot.resources.datapoints.count_f.count_f,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.INPUT,
            properties={
                'cpTypeInC':
                izot.resources.base.Profile.PropertyMember(
                    doc="""Network variable type.  Network variable type for
                    network variables that support changeable types.""",
                    name='cpTypeInC',
                    profile=self,
                    number=3,
                    datatype=izot.resources.properties.nvType.nvType,
                    default=b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01'
                        b'\x00\x01\x00\x00\x00\x00\x00\x00',
                    mandatory=True
                ),
                'cpNvLenC':
                izot.resources.base.Profile.PropertyMember(
                    doc="""Maximum network variable length.  Maximum length
                    of a type that may be assigned to the network
                    variable.""",
                    name='cpNvLenC',
                    profile=self,
                    number=19,
                    datatype=izot.resources.properties.maxNVLength.maxNVLength,
                    default=b'\x04',
                    mandatory=True
                )
            }
        )
        self.datapoints['nviDpD'] = izot.resources.base.Profile.DatapointMember(
            doc="""Absolute count.  """,
            name='nviDpD',
            profile=self,
            number=4,
            datatype=izot.resources.datapoints.count_f.count_f,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.INPUT,
            properties={
                'cpTypeInD':
                izot.resources.base.Profile.PropertyMember(
                    doc="""Network variable type.  Network variable type for
                    network variables that support changeable types.""",
                    name='cpTypeInD',
                    profile=self,
                    number=4,
                    datatype=izot.resources.properties.nvType.nvType,
                    default=b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01'
                        b'\x00\x01\x00\x00\x00\x00\x00\x00',
                    mandatory=True
                ),
                'cpNvLenD':
                izot.resources.base.Profile.PropertyMember(
                    doc="""Maximum network variable length.  Maximum length
                    of a type that may be assigned to the network
                    variable.""",
                    name='cpNvLenD',
                    profile=self,
                    number=20,
                    datatype=izot.resources.properties.maxNVLength.maxNVLength,
                    default=b'\x04',
                    mandatory=True
                )
            }
        )
        self.datapoints['nvoDpA'] = izot.resources.base.Profile.DatapointMember(
            doc="""Absolute count.  """,
            name='nvoDpA',
            profile=self,
            number=5,
            datatype=izot.resources.datapoints.count_f.count_f,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.OUTPUT,
            properties={
                'cpTypeOutA':
                izot.resources.base.Profile.PropertyMember(
                    doc="""Network variable type.  Network variable type for
                    network variables that support changeable types.""",
                    name='cpTypeOutA',
                    profile=self,
                    number=5,
                    datatype=izot.resources.properties.nvType.nvType,
                    default=b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01'
                        b'\x00\x01\x00\x00\x00\x00\x00\x00',
                    mandatory=True
                ),
                'cpMapA':
                izot.resources.base.Profile.PropertyMember(
                    doc=""" """,
                    name='cpMapA',
                    profile=self,
                    number=9,
                    datatype=P9000010600000000_4.properties.point.point,
                    default=b'\x00',
                    mandatory=True
                ),
                'cpOpA':
                izot.resources.base.Profile.PropertyMember(
                    doc=""" """,
                    name='cpOpA',
                    profile=self,
                    number=13,
                    datatype=P9000010600000000_4.properties.mathOp.mathOp,
                    default=b'\x00',
                    mandatory=True
                ),
                'cpNvoLenA':
                izot.resources.base.Profile.PropertyMember(
                    doc="""Maximum network variable length.  Maximum length
                    of a type that may be assigned to the network
                    variable.""",
                    name='cpNvoLenA',
                    profile=self,
                    number=21,
                    datatype=izot.resources.properties.maxNVLength.maxNVLength,
                    default=b'\x04',
                    mandatory=True
                ),
                'cpDefaultA':
                izot.resources.base.Profile.PropertyMember(
                    doc="""Default output.  The position or level the sensor
                    should adopt when updates are not received, or at
                    power-on reset, or when overridden.""",
                    name='cpDefaultA',
                    profile=self,
                    number=25,
                    datatype=izot.resources.properties.defOutput.defOutput,
                    default=b'\x00\x00\x00\x00',
                    mandatory=True
                )
            }
        )
        self.datapoints['nvoDpB'] = izot.resources.base.Profile.DatapointMember(
            doc="""Absolute count.  """,
            name='nvoDpB',
            profile=self,
            number=6,
            datatype=izot.resources.datapoints.count_f.count_f,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.OUTPUT,
            properties={
                'cpTypeOutB':
                izot.resources.base.Profile.PropertyMember(
                    doc="""Network variable type.  Network variable type for
                    network variables that support changeable types.""",
                    name='cpTypeOutB',
                    profile=self,
                    number=6,
                    datatype=izot.resources.properties.nvType.nvType,
                    default=b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01'
                        b'\x00\x01\x00\x00\x00\x00\x00\x00',
                    mandatory=True
                ),
                'cpMapB':
                izot.resources.base.Profile.PropertyMember(
                    doc=""" """,
                    name='cpMapB',
                    profile=self,
                    number=10,
                    datatype=P9000010600000000_4.properties.point.point,
                    default=b'\x00',
                    mandatory=True
                ),
                'cpOpB':
                izot.resources.base.Profile.PropertyMember(
                    doc=""" """,
                    name='cpOpB',
                    profile=self,
                    number=14,
                    datatype=P9000010600000000_4.properties.mathOp.mathOp,
                    default=b'\x00',
                    mandatory=True
                ),
                'cpNvoLenB':
                izot.resources.base.Profile.PropertyMember(
                    doc="""Maximum network variable length.  Maximum length
                    of a type that may be assigned to the network
                    variable.""",
                    name='cpNvoLenB',
                    profile=self,
                    number=22,
                    datatype=izot.resources.properties.maxNVLength.maxNVLength,
                    default=b'\x04',
                    mandatory=True
                ),
                'cpDefaultB':
                izot.resources.base.Profile.PropertyMember(
                    doc="""Default output.  The position or level the sensor
                    should adopt when updates are not received, or at
                    power-on reset, or when overridden.""",
                    name='cpDefaultB',
                    profile=self,
                    number=26,
                    datatype=izot.resources.properties.defOutput.defOutput,
                    default=b'\x00\x00\x00\x00',
                    mandatory=True
                )
            }
        )
        self.datapoints['nvoDpC'] = izot.resources.base.Profile.DatapointMember(
            doc="""Absolute count.  """,
            name='nvoDpC',
            profile=self,
            number=7,
            datatype=izot.resources.datapoints.count_f.count_f,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.OUTPUT,
            properties={
                'cpTypeOutC':
                izot.resources.base.Profile.PropertyMember(
                    doc="""Network variable type.  Network variable type for
                    network variables that support changeable types.""",
                    name='cpTypeOutC',
                    profile=self,
                    number=7,
                    datatype=izot.resources.properties.nvType.nvType,
                    default=b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01'
                        b'\x00\x01\x00\x00\x00\x00\x00\x00',
                    mandatory=True
                ),
                'cpMapC':
                izot.resources.base.Profile.PropertyMember(
                    doc=""" """,
                    name='cpMapC',
                    profile=self,
                    number=11,
                    datatype=P9000010600000000_4.properties.point.point,
                    default=b'\x00',
                    mandatory=True
                ),
                'cpOpC':
                izot.resources.base.Profile.PropertyMember(
                    doc=""" """,
                    name='cpOpC',
                    profile=self,
                    number=15,
                    datatype=P9000010600000000_4.properties.mathOp.mathOp,
                    default=b'\x00',
                    mandatory=True
                ),
                'cpNvoLenC':
                izot.resources.base.Profile.PropertyMember(
                    doc="""Maximum network variable length.  Maximum length
                    of a type that may be assigned to the network
                    variable.""",
                    name='cpNvoLenC',
                    profile=self,
                    number=23,
                    datatype=izot.resources.properties.maxNVLength.maxNVLength,
                    default=b'\x04',
                    mandatory=True
                ),
                'cpDefaultC':
                izot.resources.base.Profile.PropertyMember(
                    doc="""Default output.  The position or level the sensor
                    should adopt when updates are not received, or at
                    power-on reset, or when overridden.""",
                    name='cpDefaultC',
                    profile=self,
                    number=27,
                    datatype=izot.resources.properties.defOutput.defOutput,
                    default=b'\x00\x00\x00\x00',
                    mandatory=True
                )
            }
        )
        self.datapoints['nvoDpD'] = izot.resources.base.Profile.DatapointMember(
            doc="""Absolute count.  """,
            name='nvoDpD',
            profile=self,
            number=8,
            datatype=izot.resources.datapoints.count_f.count_f,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.OUTPUT,
            properties={
                'cpTypeOutD':
                izot.resources.base.Profile.PropertyMember(
                    doc="""Network variable type.  Network variable type for
                    network variables that support changeable types.""",
                    name='cpTypeOutD',
                    profile=self,
                    number=8,
                    datatype=izot.resources.properties.nvType.nvType,
                    default=b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01'
                        b'\x00\x01\x00\x00\x00\x00\x00\x00',
                    mandatory=True
                ),
                'cpMapD':
                izot.resources.base.Profile.PropertyMember(
                    doc=""" """,
                    name='cpMapD',
                    profile=self,
                    number=12,
                    datatype=P9000010600000000_4.properties.point.point,
                    default=b'\x00',
                    mandatory=True
                ),
                'cpOpD':
                izot.resources.base.Profile.PropertyMember(
                    doc=""" """,
                    name='cpOpD',
                    profile=self,
                    number=16,
                    datatype=P9000010600000000_4.properties.mathOp.mathOp,
                    default=b'\x00',
                    mandatory=True
                ),
                'cpNvoLenD':
                izot.resources.base.Profile.PropertyMember(
                    doc="""Maximum network variable length.  Maximum length
                    of a type that may be assigned to the network
                    variable.""",
                    name='cpNvoLenD',
                    profile=self,
                    number=24,
                    datatype=izot.resources.properties.maxNVLength.maxNVLength,
                    default=b'\x04',
                    mandatory=True
                ),
                'cpDefaultD':
                izot.resources.base.Profile.PropertyMember(
                    doc="""Default output.  The position or level the sensor
                    should adopt when updates are not received, or at
                    power-on reset, or when overridden.""",
                    name='cpDefaultD',
                    profile=self,
                    number=28,
                    datatype=izot.resources.properties.defOutput.defOutput,
                    default=b'\x00\x00\x00\x00',
                    mandatory=True
                )
            }
        )
        self._original_name = 'UFPT1controller'
        self._definition = userdefined.add(self)
        self.finalize()


if __name__ == '__main__':
    # unit test code.
    item = _1controller()
    pass
