# Copyright (C) 2013-2021 Echelon Corporation.  All Rights Reserved.
# Use of this code is subject to your compliance with the terms of the
# Echelon IzoT(tm) Software Developer's Kit License Agreement which is
# available at www.echelon.com/license/izot_sdk/.

# IzoT resources contained in this file are generated by an automated
# database to source code conversion process.  Grammar and punctuation within
# the embedded documentation may not be correct, as this data is gathered and
# combined from several sources.
# Names of resources and fields or members defined within a resource are
# derived from the same sources.  Names, capitalization and aspects of source
# code formatting may fail to comply with PEP-8 and PEP-257 recommendations
# due to the automated generation of these IzoT definitions.
# Generated at 25-Aug-2021 13:17.

"""lssMonitor userdefined profile, originally defined in resource file set
apollodev 90:00:01:06:00:00:00:00-4."""


import izot.resources.base
from P9000010600000000_4.userdefined import userdefined
import izot.resources.datapoints.lev_disc
import izot.resources.datapoints.state
import P9000010600000000_4.datapoints.Sensor
import P9000010600000000_4.datapoints.FmkSetup
import izot.resources.datapoints.ppm_f


class lssMonitor(izot.resources.base.Profile):
    """lssMonitor userdefined profile.  Gas Sesnosr Monitor.  """

    def __init__(self):
        super().__init__(
            key=20010,
            scope=4
        )
        self.datapoints['nvoAlarm10'] = izot.resources.base.Profile.DatapointMember(
            doc="""Discrete level.  """,
            name='nvoAlarm10',
            profile=self,
            number=1,
            datatype=izot.resources.datapoints.lev_disc.lev_disc,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.INPUT
        )
        self.datapoints['nvoAlarm11'] = izot.resources.base.Profile.DatapointMember(
            doc="""Discrete level.  """,
            name='nvoAlarm11',
            profile=self,
            number=2,
            datatype=izot.resources.datapoints.lev_disc.lev_disc,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.INPUT
        )
        self.datapoints['nvoAlarm12'] = izot.resources.base.Profile.DatapointMember(
            doc="""Discrete level.  """,
            name='nvoAlarm12',
            profile=self,
            number=3,
            datatype=izot.resources.datapoints.lev_disc.lev_disc,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.INPUT
        )
        self.datapoints['nvoAlarm13'] = izot.resources.base.Profile.DatapointMember(
            doc="""Discrete level.  """,
            name='nvoAlarm13',
            profile=self,
            number=4,
            datatype=izot.resources.datapoints.lev_disc.lev_disc,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.INPUT
        )
        self.datapoints['nvoAlarm20'] = izot.resources.base.Profile.DatapointMember(
            doc="""Discrete level.  """,
            name='nvoAlarm20',
            profile=self,
            number=5,
            datatype=izot.resources.datapoints.lev_disc.lev_disc,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.INPUT
        )
        self.datapoints['nvoAlarm21'] = izot.resources.base.Profile.DatapointMember(
            doc="""Discrete level.  """,
            name='nvoAlarm21',
            profile=self,
            number=6,
            datatype=izot.resources.datapoints.lev_disc.lev_disc,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.INPUT
        )
        self.datapoints['nvoAlarm22'] = izot.resources.base.Profile.DatapointMember(
            doc="""Discrete level.  """,
            name='nvoAlarm22',
            profile=self,
            number=7,
            datatype=izot.resources.datapoints.lev_disc.lev_disc,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.INPUT
        )
        self.datapoints['nvoAlarm23'] = izot.resources.base.Profile.DatapointMember(
            doc="""Discrete level.  """,
            name='nvoAlarm23',
            profile=self,
            number=8,
            datatype=izot.resources.datapoints.lev_disc.lev_disc,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.INPUT
        )
        self.datapoints['nvoError'] = izot.resources.base.Profile.DatapointMember(
            doc="""State vector.  Each state is a boolean single bit value.
            SNVT_state_64 is preferred.""",
            name='nvoError',
            profile=self,
            number=9,
            datatype=izot.resources.datapoints.state.state,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.INPUT
        )
        self.datapoints['nvoMaint3'] = izot.resources.base.Profile.DatapointMember(
            doc="""Discrete level.  """,
            name='nvoMaint3',
            profile=self,
            number=10,
            datatype=izot.resources.datapoints.lev_disc.lev_disc,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.INPUT
        )
        self.datapoints['nvoSensor'] = izot.resources.base.Profile.DatapointMember(
            doc=""" """,
            name='nvoSensor',
            profile=self,
            number=11,
            datatype=P9000010600000000_4.datapoints.Sensor.Sensor,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.INPUT
        )
        self.datapoints['nvoSetup'] = izot.resources.base.Profile.DatapointMember(
            doc=""" """,
            name='nvoSetup',
            profile=self,
            number=12,
            datatype=P9000010600000000_4.datapoints.FmkSetup.FmkSetup,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.INPUT
        )
        self.datapoints['nvoState'] = izot.resources.base.Profile.DatapointMember(
            doc="""State vector.  Each state is a boolean single bit value.
            SNVT_state_64 is preferred.""",
            name='nvoState',
            profile=self,
            number=13,
            datatype=izot.resources.datapoints.state.state,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.INPUT
        )
        self.datapoints['nvoWarn0'] = izot.resources.base.Profile.DatapointMember(
            doc="""Discrete level.  """,
            name='nvoWarn0',
            profile=self,
            number=14,
            datatype=izot.resources.datapoints.lev_disc.lev_disc,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.INPUT
        )
        self.datapoints['nvoWarn1'] = izot.resources.base.Profile.DatapointMember(
            doc="""Discrete level.  """,
            name='nvoWarn1',
            profile=self,
            number=15,
            datatype=izot.resources.datapoints.lev_disc.lev_disc,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.INPUT
        )
        self.datapoints['nvoWarn2'] = izot.resources.base.Profile.DatapointMember(
            doc="""Discrete level.  """,
            name='nvoWarn2',
            profile=self,
            number=16,
            datatype=izot.resources.datapoints.lev_disc.lev_disc,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.INPUT
        )
        self.datapoints['nvoWarn3'] = izot.resources.base.Profile.DatapointMember(
            doc="""Discrete level.  """,
            name='nvoWarn3',
            profile=self,
            number=17,
            datatype=izot.resources.datapoints.lev_disc.lev_disc,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.INPUT
        )
        self.datapoints['nvoFault0'] = izot.resources.base.Profile.DatapointMember(
            doc="""Discrete level.  """,
            name='nvoFault0',
            profile=self,
            number=18,
            datatype=izot.resources.datapoints.lev_disc.lev_disc,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.INPUT
        )
        self.datapoints['nvoFault1'] = izot.resources.base.Profile.DatapointMember(
            doc="""Discrete level.  """,
            name='nvoFault1',
            profile=self,
            number=19,
            datatype=izot.resources.datapoints.lev_disc.lev_disc,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.INPUT
        )
        self.datapoints['nvoFault2'] = izot.resources.base.Profile.DatapointMember(
            doc="""Discrete level.  """,
            name='nvoFault2',
            profile=self,
            number=20,
            datatype=izot.resources.datapoints.lev_disc.lev_disc,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.INPUT
        )
        self.datapoints['nvoFault3'] = izot.resources.base.Profile.DatapointMember(
            doc="""Discrete level.  """,
            name='nvoFault3',
            profile=self,
            number=21,
            datatype=izot.resources.datapoints.lev_disc.lev_disc,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.INPUT
        )
        self.datapoints['nvoGasConc'] = izot.resources.base.Profile.DatapointMember(
            doc="""Concentration """,
            name='nvoGasConc',
            profile=self,
            number=22,
            datatype=izot.resources.datapoints.ppm_f.ppm_f,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.INPUT
        )
        self.datapoints['nvoMaint0'] = izot.resources.base.Profile.DatapointMember(
            doc="""Discrete level.  """,
            name='nvoMaint0',
            profile=self,
            number=23,
            datatype=izot.resources.datapoints.lev_disc.lev_disc,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.INPUT
        )
        self.datapoints['nvoMaint1'] = izot.resources.base.Profile.DatapointMember(
            doc="""Discrete level.  """,
            name='nvoMaint1',
            profile=self,
            number=24,
            datatype=izot.resources.datapoints.lev_disc.lev_disc,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.INPUT
        )
        self.datapoints['nvoMaint2'] = izot.resources.base.Profile.DatapointMember(
            doc="""Discrete level.  """,
            name='nvoMaint2',
            profile=self,
            number=25,
            datatype=izot.resources.datapoints.lev_disc.lev_disc,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.INPUT
        )
        self._original_name = 'UFPTlssMonitor'
        self._definition = userdefined.add(self)
        self.finalize()


if __name__ == '__main__':
    # unit test code.
    item = lssMonitor()
    pass
