# Copyright (C) 2013-2021 Echelon Corporation.  All Rights Reserved.
# Use of this code is subject to your compliance with the terms of the
# Echelon IzoT(tm) Software Developer's Kit License Agreement which is
# available at www.echelon.com/license/izot_sdk/.

# IzoT resources contained in this file are generated by an automated
# database to source code conversion process.  Grammar and punctuation within
# the embedded documentation may not be correct, as this data is gathered and
# combined from several sources.
# Names of resources and fields or members defined within a resource are
# derived from the same sources.  Names, capitalization and aspects of source
# code formatting may fail to comply with PEP-8 and PEP-257 recommendations
# due to the automated generation of these IzoT definitions.
# Generated at 25-Aug-2021 13:17.

"""switchDriver userdefined profile, originally defined in resource file set
apollodev 90:00:01:06:00:00:00:00-4."""


import izot.resources.base
from P9000010600000000_4.userdefined import userdefined
import izot.resources.datapoints.switch


class switchDriver(izot.resources.base.Profile):
    """switchDriver userdefined profile.  """

    def __init__(self):
        super().__init__(
            key=20014,
            scope=4
        )
        self.datapoints['nvoSwitch01'] = izot.resources.base.Profile.DatapointMember(
            doc="""Switch """,
            name='nvoSwitch01',
            profile=self,
            number=1,
            datatype=izot.resources.datapoints.switch.switch,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.OUTPUT
        )
        self.datapoints['nvoSwitch02'] = izot.resources.base.Profile.DatapointMember(
            doc="""Switch """,
            name='nvoSwitch02',
            profile=self,
            number=2,
            datatype=izot.resources.datapoints.switch.switch,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.OUTPUT
        )
        self.datapoints['nvoSwitch03'] = izot.resources.base.Profile.DatapointMember(
            doc="""Switch """,
            name='nvoSwitch03',
            profile=self,
            number=3,
            datatype=izot.resources.datapoints.switch.switch,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.OUTPUT
        )
        self.datapoints['nvoSwitch04'] = izot.resources.base.Profile.DatapointMember(
            doc="""Switch """,
            name='nvoSwitch04',
            profile=self,
            number=4,
            datatype=izot.resources.datapoints.switch.switch,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.OUTPUT
        )
        self.datapoints['nvoSwitch05'] = izot.resources.base.Profile.DatapointMember(
            doc="""Switch """,
            name='nvoSwitch05',
            profile=self,
            number=5,
            datatype=izot.resources.datapoints.switch.switch,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.OUTPUT
        )
        self.datapoints['nvoSwitch06'] = izot.resources.base.Profile.DatapointMember(
            doc="""Switch """,
            name='nvoSwitch06',
            profile=self,
            number=6,
            datatype=izot.resources.datapoints.switch.switch,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.OUTPUT
        )
        self.datapoints['nvoSwitch07'] = izot.resources.base.Profile.DatapointMember(
            doc="""Switch """,
            name='nvoSwitch07',
            profile=self,
            number=7,
            datatype=izot.resources.datapoints.switch.switch,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.OUTPUT
        )
        self.datapoints['nvoSwitch08'] = izot.resources.base.Profile.DatapointMember(
            doc="""Switch """,
            name='nvoSwitch08',
            profile=self,
            number=8,
            datatype=izot.resources.datapoints.switch.switch,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.OUTPUT
        )
        self._original_name = 'UFPTswitchDriver'
        self._definition = userdefined.add(self)
        self.finalize()


if __name__ == '__main__':
    # unit test code.
    item = switchDriver()
    pass
