# Copyright (C) 2013-2021 Echelon Corporation.  All Rights Reserved.
# Use of this code is subject to your compliance with the terms of the
# Echelon IzoT(tm) Software Developer's Kit License Agreement which is
# available at www.echelon.com/license/izot_sdk/.

# IzoT resources contained in this file are generated by an automated
# database to source code conversion process.  Grammar and punctuation within
# the embedded documentation may not be correct, as this data is gathered and
# combined from several sources.
# Names of resources and fields or members defined within a resource are
# derived from the same sources.  Names, capitalization and aspects of source
# code formatting may fail to comply with PEP-8 and PEP-257 recommendations
# due to the automated generation of these IzoT definitions.
# Generated at 25-Aug-2021 13:17.

"""webServerMon userdefined profile, originally defined in resource file set
apollodev 90:00:01:06:00:00:00:00-4."""


import izot.resources.base
from P9000010600000000_4.userdefined import userdefined
import izot.resources.datapoints.alarm_2


class webServerMon(izot.resources.base.Profile):
    """webServerMon userdefined profile.  """

    def __init__(self):
        super().__init__(
            key=20013,
            scope=4
        )
        self.datapoints['alarm'] = izot.resources.base.Profile.DatapointMember(
            doc="""Alarm status 2.  Used to report alarm status for a
            functional block or device.  Replaces SNVT_alarm.""",
            name='alarm',
            profile=self,
            number=1,
            datatype=izot.resources.datapoints.alarm_2.alarm_2,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.OUTPUT
        )
        self._original_name = 'UFPTwebServerMon'
        self._definition = userdefined.add(self)
        self.finalize()


if __name__ == '__main__':
    # unit test code.
    item = webServerMon()
    pass
