# Copyright (C) 2013-2023 Echelon Corporation.  All Rights Reserved.
# Use of this code is subject to your compliance with the terms of the
# Echelon IzoT(tm) Software Developer's Kit License Agreement which is
# available at www.echelon.com/license/izot_sdk/.

# IzoT resources contained in this file are generated by an automated
# database to source code conversion process.  Grammar and punctuation within
# the embedded documentation may not be correct, as this data is gathered and
# combined from several sources.
# Names of resources and fields or members defined within a resource are
# derived from the same sources.  Names, capitalization and aspects of source
# code formatting may fail to comply with PEP-8 and PEP-257 recommendations
# due to the automated generation of these IzoT definitions.
# Generated at 11-May-2023 17:11.

"""sbs_cntrl userdefined enumeration type, originally defined in resource
file set apollodev 90:00:01:06:00:00:00:00-4."""


import izot.resources.base
from P9000010600000000_4.userdefined import userdefined


class sbs_cntrl(izot.resources.base.Enumeration):
    """sbs_cntrl userdefined enumeration."""

    MEM_NUL = -1

    # NOTE member STARTUP was renamed to MEM_ to obtain a common prefix
    # throughout this enumeration.
    MEM_ = 0

    # NOTE member DISABLE was renamed to MEM_ to obtain a common prefix
    # throughout this enumeration.
    MEM_ = 1

    # NOTE member ACTIVE was renamed to MEM_ to obtain a common prefix
    # throughout this enumeration.
    MEM_ = 2

    # NOTE member REBUILD was renamed to MEM_ to obtain a common prefix
    # throughout this enumeration.
    MEM_ = 3

    # NOTE member BUILD_ACTIVE was renamed to MEM_ACTIVE to obtain a common
    # prefix throughout this enumeration.
    MEM_ACTIVE = 4

    # NOTE member SBS_DOWN was renamed to MEM_DOWN to obtain a common prefix
    # throughout this enumeration.
    MEM_DOWN = 5

    def __init__(self):
        super().__init__(
            key=8,
            scope=4,
            prefix='MEM_'
        )
        self._original_name = 'sbs_cntrl'
        self._definition = userdefined.add(self)


if __name__ == '__main__':
    # unit test code.
    item = sbs_cntrl()
    pass
