# Copyright (C) 2013-2021 Echelon Corporation.  All Rights Reserved.
# Use of this code is subject to your compliance with the terms of the
# Echelon IzoT(tm) Software Developer's Kit License Agreement which is
# available at www.echelon.com/license/izot_sdk/.

# IzoT resources contained in this file are generated by an automated
# database to source code conversion process.  Grammar and punctuation within
# the embedded documentation may not be correct, as this data is gathered and
# combined from several sources.
# Names of resources and fields or members defined within a resource are
# derived from the same sources.  Names, capitalization and aspects of source
# code formatting may fail to comply with PEP-8 and PEP-257 recommendations
# due to the automated generation of these IzoT definitions.
# Generated at 24-Aug-2021 09:17.

"""destTarget userdefined property type, originally defined in resource file
set apollodev 90:00:01:06:00:00:00:00-4."""


import P9000010600000000_4.datapoints.destTarget
from P9000010600000000_4.userdefined import userdefined


class destTarget(P9000010600000000_4.datapoints.destTarget.destTarget):
    """destTarget userdefined property type.  ."""

    def __init__(self):
        super().__init__(
        )
        self._default_bytes = b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' \
            b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' \
            b'\x00'
        self._original_name = 'UCPTdestTarget'
        self._property_scope, self._property_key = 4, 4
        self._definition = userdefined.add(self)


if __name__ == '__main__':
    # unit test code.
    item = destTarget()
    pass
