# Copyright (C) 2013-2019 Echelon Corporation.  All Rights Reserved.
# Use of this code is subject to your compliance with the terms of the
# Echelon IzoT(tm) Software Developer's Kit License Agreement which is
# available at www.echelon.com/license/izot_sdk/.

# IzoT resources contained in this file are generated by an automated
# database to source code conversion process.  Grammar and punctuation within
# the embedded documentation may not be correct, as this data is gathered and
# combined from several sources.
# Names of resources and fields or members defined within a resource are
# derived from the same sources.  Names, capitalization and aspects of source
# code formatting may fail to comply with PEP-8 and PEP-257 recommendations
# due to the automated generation of these IzoT definitions.
# Generated at 17-Aug-2019 06:56.

"""displayController2 userdefined profile, originally defined in resource
file set apollodev 90:00:01:06:00:00:00:00-4."""


import izot.resources.base
from P9000010600000000_4.userdefined import userdefined
import izot.resources.datapoints.str_asc
import P9000010600000000_4.properties.msgDefault
import izot.resources.datapoints.count


class displayController2(izot.resources.base.Profile):
    """displayController2 userdefined profile.  """

    def __init__(self):
        super().__init__(
            key=20001,
            scope=4,
            principal='nviLine1msg'
        )
        self.datapoints['nviLine1msg'] = izot.resources.base.Profile.DatapointMember(
            doc="""Character string (30 characters max) """,
            name='nviLine1msg',
            profile=self,
            number=1,
            datatype=izot.resources.datapoints.str_asc.str_asc,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.INPUT,
            properties={
                'cpLine1Default':
                izot.resources.base.Profile.PropertyMember(
                    doc=""" """,
                    name='cpLine1Default',
                    profile=self,
                    number=1,
                    datatype=P9000010600000000_4.properties.msgDefault.msgDefault,
                    default=b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
                        b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
                        b'\x00\x00\x00\x00\x00\x00\x00\x00\x00',
                    mandatory=True
                )
            }
        )
        self.datapoints['nviLine2msg'] = izot.resources.base.Profile.DatapointMember(
            doc="""Character string (30 characters max) """,
            name='nviLine2msg',
            profile=self,
            number=2,
            datatype=izot.resources.datapoints.str_asc.str_asc,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.INPUT,
            properties={
                'cpLine2Default':
                izot.resources.base.Profile.PropertyMember(
                    doc=""" """,
                    name='cpLine2Default',
                    profile=self,
                    number=2,
                    datatype=P9000010600000000_4.properties.msgDefault.msgDefault,
                    default=b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
                        b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
                        b'\x00\x00\x00\x00\x00\x00\x00\x00\x00',
                    mandatory=True
                )
            }
        )
        self.datapoints['nviLine3msg'] = izot.resources.base.Profile.DatapointMember(
            doc="""Character string (30 characters max) """,
            name='nviLine3msg',
            profile=self,
            number=3,
            datatype=izot.resources.datapoints.str_asc.str_asc,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.INPUT,
            properties={
                'cpLine3Default':
                izot.resources.base.Profile.PropertyMember(
                    doc=""" """,
                    name='cpLine3Default',
                    profile=self,
                    number=3,
                    datatype=P9000010600000000_4.properties.msgDefault.msgDefault,
                    default=b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
                        b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
                        b'\x00\x00\x00\x00\x00\x00\x00\x00\x00',
                    mandatory=True
                )
            }
        )
        self.datapoints['nvoMyNid'] = izot.resources.base.Profile.DatapointMember(
            doc="""Character string (30 characters max) """,
            name='nvoMyNid',
            profile=self,
            number=4,
            datatype=izot.resources.datapoints.str_asc.str_asc,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.OUTPUT
        )
        self.datapoints['nvoWinkCount'] = izot.resources.base.Profile.DatapointMember(
            doc="""Absolute count.  """,
            name='nvoWinkCount',
            profile=self,
            number=5,
            datatype=izot.resources.datapoints.count.count,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.OUTPUT
        )
        self.datapoints['nvoSimpleUpDown'] = izot.resources.base.Profile.DatapointMember(
            doc="""Absolute count.  """,
            name='nvoSimpleUpDown',
            profile=self,
            number=6,
            datatype=izot.resources.datapoints.count.count,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.OUTPUT
        )
        self._original_name = 'UFPTdisplayController2'
        self._definition = userdefined.add(self)
        self.finalize()


if __name__ == '__main__':
    # unit test code.
    item = displayController2()
    pass
