# Copyright (C) 2013-2020 Echelon Corporation.  All Rights Reserved.
# Use of this code is subject to your compliance with the terms of the
# Echelon IzoT(tm) Software Developer's Kit License Agreement which is
# available at www.echelon.com/license/izot_sdk/.

# IzoT resources contained in this file are generated by an automated
# database to source code conversion process.  Grammar and punctuation within
# the embedded documentation may not be correct, as this data is gathered and
# combined from several sources.
# Names of resources and fields or members defined within a resource are
# derived from the same sources.  Names, capitalization and aspects of source
# code formatting may fail to comply with PEP-8 and PEP-257 recommendations
# due to the automated generation of these IzoT definitions.
# Generated at 18-Nov-2020 16:22.

"""LoRaGateway userdefined profile, originally defined in resource file set
r00001xxxxxxxxxx 90:00:01:00:00:00:00:00-3."""


import izot.resources.base
from P9000010000000000_3.userdefined import userdefined
import izot.resources.datapoints.temp_p
import izot.resources.datapoints.lev_cont_f
import izot.resources.datapoints.ppm_f
import izot.resources.datapoints.lux


class LoRaGateway(izot.resources.base.Profile):
    """LoRaGateway userdefined profile.  """

    def __init__(self):
        super().__init__(
            key=20000,
            scope=3
        )
        self.datapoints['nvoTemp'] = izot.resources.base.Profile.DatapointMember(
            doc="""Temperature """,
            name='nvoTemp',
            profile=self,
            number=1,
            datatype=izot.resources.datapoints.temp_p.temp_p,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.OUTPUT
        )
        self.datapoints['nvoRH'] = izot.resources.base.Profile.DatapointMember(
            doc="""Continuous level.  """,
            name='nvoRH',
            profile=self,
            number=2,
            datatype=izot.resources.datapoints.lev_cont_f.lev_cont_f,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.OUTPUT
        )
        self.datapoints['nvoCO2'] = izot.resources.base.Profile.DatapointMember(
            doc="""Concentration """,
            name='nvoCO2',
            profile=self,
            number=3,
            datatype=izot.resources.datapoints.ppm_f.ppm_f,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.OUTPUT
        )
        self.datapoints['nvoLux'] = izot.resources.base.Profile.DatapointMember(
            doc="""Illumination """,
            name='nvoLux',
            profile=self,
            number=5,
            datatype=izot.resources.datapoints.lux.lux,
            mandatory=True,
            direction=izot.resources.base.Profile.DatapointMember.OUTPUT
        )
        self._original_name = 'UFPTLoRaGateway'
        self._definition = userdefined.add(self)
        self.finalize()


if __name__ == '__main__':
    # unit test code.
    item = LoRaGateway()
    pass
