# Copyright (C) 2013-2021 Echelon Corporation.  All Rights Reserved.
# Use of this code is subject to your compliance with the terms of the
# Echelon IzoT(tm) Software Developer's Kit License Agreement which is
# available at www.echelon.com/license/izot_sdk/.

# IzoT resources contained in this file are generated by an automated
# database to source code conversion process.  Grammar and punctuation within
# the embedded documentation may not be correct, as this data is gathered and
# combined from several sources.
# Names of resources and fields or members defined within a resource are
# derived from the same sources.  Names, capitalization and aspects of source
# code formatting may fail to comply with PEP-8 and PEP-257 recommendations
# due to the automated generation of these IzoT definitions.
# Generated at 24-Aug-2021 09:17.

"""gmState userdefined enumeration type, originally defined in resource file
set apollodev 90:00:01:06:00:00:00:00-4."""


import izot.resources.base
from P9000010600000000_4.userdefined import userdefined


class gmState(izot.resources.base.Enumeration):
    """gmState userdefined enumeration."""

    GMS_NULL = -1

    GMS_PAUSED = 0

    GMS_STARTED = 1

    # NOTE member Member_2 was renamed to GMS_2 to obtain a common prefix
    # throughout this enumeration.
    GMS_2 = 2

    def __init__(self):
        super().__init__(
            key=4,
            scope=4,
            prefix='GMS_'
        )
        self._original_name = 'gmState'
        self._definition = userdefined.add(self)


if __name__ == '__main__':
    # unit test code.
    item = gmState()
    pass
