# Copyright (C) 2013-2021 Echelon Corporation.  All Rights Reserved.
# Use of this code is subject to your compliance with the terms of the
# Echelon IzoT(tm) Software Developer's Kit License Agreement which is
# available at www.echelon.com/license/izot_sdk/.

# IzoT resources contained in this file are generated by an automated
# database to source code conversion process.  Grammar and punctuation within
# the embedded documentation may not be correct, as this data is gathered and
# combined from several sources.
# Names of resources and fields or members defined within a resource are
# derived from the same sources.  Names, capitalization and aspects of source
# code formatting may fail to comply with PEP-8 and PEP-257 recommendations
# due to the automated generation of these IzoT definitions.
# Generated at 24-Aug-2021 09:17.

"""pass_t userdefined enumeration type, originally defined in resource file
set apollodev 90:00:01:06:00:00:00:00-4."""


import izot.resources.base
from P9000010600000000_4.userdefined import userdefined


class pass_t(izot.resources.base.Enumeration):
    """pass_t userdefined enumeration."""

    PASSWORD_ON = 0

    PASSWORD_OFF = 1

    def __init__(self):
        super().__init__(
            key=3,
            scope=4,
            prefix='PASSWORD_'
        )
        self._original_name = 'pass_t'
        self._definition = userdefined.add(self)


if __name__ == '__main__':
    # unit test code.
    item = pass_t()
    pass
