# Copyright (C) 2013-2021 Echelon Corporation.  All Rights Reserved.
# Use of this code is subject to your compliance with the terms of the
# Echelon IzoT(tm) Software Developer's Kit License Agreement which is
# available at www.echelon.com/license/izot_sdk/.

# IzoT resources contained in this file are generated by an automated
# database to source code conversion process.  Grammar and punctuation within
# the embedded documentation may not be correct, as this data is gathered and
# combined from several sources.
# Names of resources and fields or members defined within a resource are
# derived from the same sources.  Names, capitalization and aspects of source
# code formatting may fail to comply with PEP-8 and PEP-257 recommendations
# due to the automated generation of these IzoT definitions.
# Generated at 24-Aug-2021 09:17.

"""WaveForms userdefined enumeration type, originally defined in resource
file set apollodev 90:00:01:06:00:00:00:00-4."""


import izot.resources.base
from P9000010600000000_4.userdefined import userdefined


class WaveForms(izot.resources.base.Enumeration):
    """WaveForms userdefined enumeration."""

    MEM_NUL = -1

    # NOTE member WV_SAWTOOTH was renamed to MEM_SAWTOOTH to obtain a common
    # prefix throughout this enumeration.
    # Sawtooth.
    MEM_SAWTOOTH = 0

    # NOTE member WV_RAMP was renamed to MEM_RAMP to obtain a common prefix
    # throughout this enumeration.
    # Ramp.
    MEM_RAMP = 1

    # NOTE member WV_SQUARE was renamed to MEM_SQUARE to obtain a common
    # prefix throughout this enumeration.
    # Ramp.
    MEM_SQUARE = 2

    def __init__(self):
        super().__init__(
            key=2,
            scope=4,
            prefix='MEM_'
        )
        self._original_name = 'WaveForms'
        self._definition = userdefined.add(self)


if __name__ == '__main__':
    # unit test code.
    item = WaveForms()
    pass
