# Copyright (C) 2013-2020 Echelon Corporation.  All Rights Reserved.
# Use of this code is subject to your compliance with the terms of the
# Echelon IzoT(tm) Software Developer's Kit License Agreement which is
# available at www.echelon.com/license/izot_sdk/.

# IzoT resources contained in this file are generated by an automated
# database to source code conversion process.  Grammar and punctuation within
# the embedded documentation may not be correct, as this data is gathered and
# combined from several sources.
# Names of resources and fields or members defined within a resource are
# derived from the same sources.  Names, capitalization and aspects of source
# code formatting may fail to comply with PEP-8 and PEP-257 recommendations
# due to the automated generation of these IzoT definitions.
# Generated at 18-Nov-2020 16:22.

"""standard - a re-usable DRF definition object.  DRF definition objects are
used to document the source of a IzoTresource derived from a device resource
file (DRF)."""


import izot.resources.base

standard = izot.resources.base.Drf(
    program_id='00:00:00:00:00:00:00:00',
    scope=0,
    name='standard',
    version=(16, 0),
    doc="""This file is the standard type file, containing Standard Network
    Variable Types (SNVTs), Standard Configuration Property Types (SCPTs),
    and the enumeration types that support them.  This file was created and
    is maintained by LonMark International.  Contact us at +1-408-938-5266,
    at http://www.lonmark.org, or at 550 Meridian Ave, San Jose CA 95126,
    USA."""
)
